name: Send Smart-Random Proxy to Telegram

on:
  schedule:
    # اجرا هر 5 دقیقه
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # دسترسی نوشتن برای ذخیره فایل حافظه ضروری است
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script to send one smart-random proxy
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
        
      - name: Commit recent proxies file
        run: |
          # بررسی کن که آیا فایل حافظه وجود دارد یا خیر
          if [ -f recent_proxies.txt ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add recent_proxies.txt
            # فقط در صورتی کامیت کن که تغییری در فایل حافظه وجود داشته باشد
            git diff --staged --quiet || (git commit -m "Update recent proxies memory" && git push)
          else
            echo "Recent proxies file not found, skipping commit."
          fi
